### ISSUE TITLE
Roadmap 2.0.0

### ISSUE THREAD

**Issue by thasmo** [packmule/packmule#25]
- [ ] Split project into separate packages using a monorepo.
- [ ] Integrate support for webpack 5.
- [ ] Write unit tests for all packages.
- [ ] Enrich documentation.
- [ ] Create a migration document.
- [ ] Create a changelog document.
